name: android release

on:
  push:
    tags:
      - "*-android"

permissions:
  contents: write

jobs:
  android-release:
    runs-on: lynx-ubuntu-22.04-physical-medium
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 7.33.6
      - name: Get Tag Information
        run: |-
          version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
          version=$(echo "$version" | awk -F "-android" '{print $1}')
          echo "VERSION=$version" >> $GITHUB_OUTPUT;
        id: get_tag
      - name: Grant execute permission for gradlew
        run: cd $GITHUB_WORKSPACE/test/e2e_test/android_example &&  chmod +x ./gradlew
      - name: Build artifact
        run: |-
          source tools/envsetup.sh
          pushd test/e2e_test/android_example
          ./gradlew :DebugRouter:assemblerelease
          ./gradlew :DebugRouter:publish \
          -Pversion=${{ steps.get_tag.outputs.VERSION }} \
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
          -Psigning.secretKey=${{ secrets.SIGNING_SECRET_KEY }}
          ./gradlew :DebugRouter:zipArtifacts -Pversion=${{ steps.get_tag.outputs.VERSION }} :DebugRouter:getArtifactList
          popd
          pushd debug_router/android/debug_router/build/
          artifact_list=$(<artifact-list)
          echo $artifact_list
          echo "::set-output name=artifact_list::$artifact_list"
          popd
        id: build_artifact
      - name: Publish artifact to maven
        uses: lynx-infra/maven-publish-action@c48e3067642c7ceccf807cd52e6644a257cd8ded
        with:
          portal_api_token: ${{ secrets.PORTAL_API_TOKEN }}
          artifact_path_list: ${{ steps.build_artifact.outputs.artifact_list }}
